name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust
          shared-key: ${{ matrix.target }}@release
      - name: Build
        run: |
          cargo build --release
          tar -czf ipass-${{ matrix.target }}.tar.gz -C target/release ipass
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipass-${{ matrix.target }}
          path: ipass-${{ matrix.target }}.tar.gz

  draft:
    permissions:
      contents: write
    runs-on: macos-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ipass-*
          generate_release_notes: true

